{"name": "Addition", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\dell\\Desktop\\Bootcamp\\CICD\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\dell\\Desktop\\Bootcamp\\CICD\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\calcSteps.py\", line 23, in step_then_check_answer\n    assert actual_answer == expected_answer\n"}, "steps": [{"name": "Given I have a calculator", "status": "passed", "start": 1689108121690, "stop": 1689108121690}, {"name": "When I enter \"5\" as the first number", "status": "passed", "start": 1689108121690, "stop": 1689108121691}, {"name": "And I enter \"+\" as the operation", "status": "passed", "start": 1689108121692, "stop": 1689108121692}, {"name": "And I enter \"3\" as the second number", "status": "passed", "start": 1689108121693, "stop": 1689108121693}, {"name": "Then the answer should be \"8\"", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\dell\\Desktop\\Bootcamp\\CICD\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\dell\\Desktop\\Bootcamp\\CICD\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\calcSteps.py\", line 23, in step_then_check_answer\n    assert actual_answer == expected_answer\n"}, "start": 1689108121694, "stop": 1689108121696}], "start": 1689108121674, "stop": 1689108121696, "uuid": "845a8c32-f812-4c1d-a120-7d750f2937a8", "historyId": "b625f9cfd64fefca5aa75206fe3e433f", "fullName": "Calculator: Addition", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Calculator"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}