{"name": "Addition", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\dell\\Desktop\\Bootcamp\\CICD\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\dell\\Desktop\\Bootcamp\\CICD\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\calcSteps.py\", line 22, in step_then_check_answer\n    assert actual_answer == expected_answer\n"}, "steps": [{"name": "Given I have a calculator", "status": "passed", "start": 1689109998663, "stop": 1689109998664}, {"name": "When I enter \"5\" as the first number", "status": "passed", "start": 1689109998665, "stop": 1689109998667}, {"name": "And I enter \"+\" as the operation", "status": "passed", "start": 1689109998667, "stop": 1689109998669}, {"name": "And I enter \"3\" as the second number", "status": "passed", "start": 1689109998669, "stop": 1689109998671}, {"name": "Then the answer should be \"8\"", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\dell\\Desktop\\Bootcamp\\CICD\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\dell\\Desktop\\Bootcamp\\CICD\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\calcSteps.py\", line 22, in step_then_check_answer\n    assert actual_answer == expected_answer\n"}, "start": 1689109998671, "stop": 1689109998674}], "start": 1689109998637, "stop": 1689109998674, "uuid": "eee4a39f-7e8f-4d1d-a8cc-54e962e0a009", "historyId": "b625f9cfd64fefca5aa75206fe3e433f", "fullName": "Calculator: Addition", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Calculator"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}